server:
  port: "8080"
  mode: "debug"

database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: ""
  name: "ujian"

jwt:
  secret: "school-exam-system-secret-key-2024"
  expire_hour: 24